//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SYSPRO.NET.BusinessObjects.CSHQSOOUT {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CashBookOptions {
        
        private GeneralType generalField;
        
        private HistoryType historyField;
        
        private TaxType taxField;
        
        private PeriodCurrentYearType periodCurrentYearField;
        
        private PeriodPreviousYearType periodPreviousYearField;
        
        private CurrentMonthType currentMonthField;
        
        private InformationType informationField;
        
        private sbyte languageField;
        
        private string language2Field;
        
        private string cssStyleField;
        
        private bool decFormatField;
        
        private sbyte dateFormatField;
        
        private sbyte roleField;
        
        private string versionField;
        
        private string operatorPrimaryRoleField;
        
        /// <remarks/>
        public GeneralType General {
            get {
                return this.generalField;
            }
            set {
                this.generalField = value;
            }
        }
        
        /// <remarks/>
        public HistoryType History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
            }
        }
        
        /// <remarks/>
        public TaxType Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public PeriodCurrentYearType PeriodCurrentYear {
            get {
                return this.periodCurrentYearField;
            }
            set {
                this.periodCurrentYearField = value;
            }
        }
        
        /// <remarks/>
        public PeriodPreviousYearType PeriodPreviousYear {
            get {
                return this.periodPreviousYearField;
            }
            set {
                this.periodPreviousYearField = value;
            }
        }
        
        /// <remarks/>
        public CurrentMonthType CurrentMonth {
            get {
                return this.currentMonthField;
            }
            set {
                this.currentMonthField = value;
            }
        }
        
        /// <remarks/>
        public InformationType Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language2 {
            get {
                return this.language2Field;
            }
            set {
                this.language2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CssStyle {
            get {
                return this.cssStyleField;
            }
            set {
                this.cssStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DecFormat {
            get {
                return this.decFormatField;
            }
            set {
                this.decFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte DateFormat {
            get {
                return this.dateFormatField;
            }
            set {
                this.dateFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorPrimaryRole {
            get {
                return this.operatorPrimaryRoleField;
            }
            set {
                this.operatorPrimaryRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneralType {
        
        private string foreignCurrCashBookReqField;
        
        private string permEntReqCbField;
        
        private string askNotPerDetDistrEntryField;
        
        private string dispBankBalInRecapScreenField;
        
        private string autoBankReconOfDepositsField;
        
        /// <remarks/>
        public string ForeignCurrCashBookReq {
            get {
                return this.foreignCurrCashBookReqField;
            }
            set {
                this.foreignCurrCashBookReqField = value;
            }
        }
        
        /// <remarks/>
        public string PermEntReqCb {
            get {
                return this.permEntReqCbField;
            }
            set {
                this.permEntReqCbField = value;
            }
        }
        
        /// <remarks/>
        public string AskNotPerDetDistrEntry {
            get {
                return this.askNotPerDetDistrEntryField;
            }
            set {
                this.askNotPerDetDistrEntryField = value;
            }
        }
        
        /// <remarks/>
        public string DispBankBalInRecapScreen {
            get {
                return this.dispBankBalInRecapScreenField;
            }
            set {
                this.dispBankBalInRecapScreenField = value;
            }
        }
        
        /// <remarks/>
        public string AutoBankReconOfDeposits {
            get {
                return this.autoBankReconOfDepositsField;
            }
            set {
                this.autoBankReconOfDepositsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InformationType {
        
        private sbyte cbNextJnlPrevYearField;
        
        private sbyte cbNextJnlCurrYearField;
        
        private sbyte cbNextJnlNextYearField;
        
        private sbyte cbNextPayRegPrevYearField;
        
        private sbyte cbNextPayRegCurrYearField;
        
        private sbyte cbNextPayRegNextYearField;
        
        /// <remarks/>
        public sbyte CbNextJnlPrevYear {
            get {
                return this.cbNextJnlPrevYearField;
            }
            set {
                this.cbNextJnlPrevYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CbNextJnlCurrYear {
            get {
                return this.cbNextJnlCurrYearField;
            }
            set {
                this.cbNextJnlCurrYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CbNextJnlNextYear {
            get {
                return this.cbNextJnlNextYearField;
            }
            set {
                this.cbNextJnlNextYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CbNextPayRegPrevYear {
            get {
                return this.cbNextPayRegPrevYearField;
            }
            set {
                this.cbNextPayRegPrevYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CbNextPayRegCurrYear {
            get {
                return this.cbNextPayRegCurrYearField;
            }
            set {
                this.cbNextPayRegCurrYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CbNextPayRegNextYear {
            get {
                return this.cbNextPayRegNextYearField;
            }
            set {
                this.cbNextPayRegNextYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CurrentMonthType {
        
        private short cbCurrentYearField;
        
        private sbyte glCurrentMonthField;
        
        private sbyte accPeriodsPerYearField;
        
        /// <remarks/>
        public short CbCurrentYear {
            get {
                return this.cbCurrentYearField;
            }
            set {
                this.cbCurrentYearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte GlCurrentMonth {
            get {
                return this.glCurrentMonthField;
            }
            set {
                this.glCurrentMonthField = value;
            }
        }
        
        /// <remarks/>
        public sbyte AccPeriodsPerYear {
            get {
                return this.accPeriodsPerYearField;
            }
            set {
                this.accPeriodsPerYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeriodPreviousYearType {
        
        private string cbPrevDatePeriod1Field;
        
        private string cbPrevFlagPeriod1Field;
        
        private string cbPrevDatePeriod2Field;
        
        private string cbPrevFlagPeriod2Field;
        
        private string cbPrevDatePeriod3Field;
        
        private string cbPrevFlagPeriod3Field;
        
        private string cbPrevDatePeriod4Field;
        
        private string cbPrevFlagPeriod4Field;
        
        private string cbPrevDatePeriod5Field;
        
        private string cbPrevFlagPeriod5Field;
        
        private string cbPrevDatePeriod6Field;
        
        private string cbPrevFlagPeriod6Field;
        
        private string cbPrevDatePeriod7Field;
        
        private string cbPrevFlagPeriod7Field;
        
        private string cbPrevDatePeriod8Field;
        
        private string cbPrevFlagPeriod8Field;
        
        private string cbPrevDatePeriod9Field;
        
        private string cbPrevFlagPeriod9Field;
        
        private string cbPrevDatePeriod10Field;
        
        private string cbPrevFlagPeriod10Field;
        
        private string cbPrevDatePeriod11Field;
        
        private string cbPrevFlagPeriod11Field;
        
        private string cbPrevDatePeriod12Field;
        
        private string cbPrevFlagPeriod12Field;
        
        private CbPrevDatePeriod13 cbPrevDatePeriod13Field;
        
        private string cbPrevFlagPeriod13Field;
        
        /// <remarks/>
        public string CbPrevDatePeriod1 {
            get {
                return this.cbPrevDatePeriod1Field;
            }
            set {
                this.cbPrevDatePeriod1Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod1 {
            get {
                return this.cbPrevFlagPeriod1Field;
            }
            set {
                this.cbPrevFlagPeriod1Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod2 {
            get {
                return this.cbPrevDatePeriod2Field;
            }
            set {
                this.cbPrevDatePeriod2Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod2 {
            get {
                return this.cbPrevFlagPeriod2Field;
            }
            set {
                this.cbPrevFlagPeriod2Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod3 {
            get {
                return this.cbPrevDatePeriod3Field;
            }
            set {
                this.cbPrevDatePeriod3Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod3 {
            get {
                return this.cbPrevFlagPeriod3Field;
            }
            set {
                this.cbPrevFlagPeriod3Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod4 {
            get {
                return this.cbPrevDatePeriod4Field;
            }
            set {
                this.cbPrevDatePeriod4Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod4 {
            get {
                return this.cbPrevFlagPeriod4Field;
            }
            set {
                this.cbPrevFlagPeriod4Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod5 {
            get {
                return this.cbPrevDatePeriod5Field;
            }
            set {
                this.cbPrevDatePeriod5Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod5 {
            get {
                return this.cbPrevFlagPeriod5Field;
            }
            set {
                this.cbPrevFlagPeriod5Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod6 {
            get {
                return this.cbPrevDatePeriod6Field;
            }
            set {
                this.cbPrevDatePeriod6Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod6 {
            get {
                return this.cbPrevFlagPeriod6Field;
            }
            set {
                this.cbPrevFlagPeriod6Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod7 {
            get {
                return this.cbPrevDatePeriod7Field;
            }
            set {
                this.cbPrevDatePeriod7Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod7 {
            get {
                return this.cbPrevFlagPeriod7Field;
            }
            set {
                this.cbPrevFlagPeriod7Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod8 {
            get {
                return this.cbPrevDatePeriod8Field;
            }
            set {
                this.cbPrevDatePeriod8Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod8 {
            get {
                return this.cbPrevFlagPeriod8Field;
            }
            set {
                this.cbPrevFlagPeriod8Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod9 {
            get {
                return this.cbPrevDatePeriod9Field;
            }
            set {
                this.cbPrevDatePeriod9Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod9 {
            get {
                return this.cbPrevFlagPeriod9Field;
            }
            set {
                this.cbPrevFlagPeriod9Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod10 {
            get {
                return this.cbPrevDatePeriod10Field;
            }
            set {
                this.cbPrevDatePeriod10Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod10 {
            get {
                return this.cbPrevFlagPeriod10Field;
            }
            set {
                this.cbPrevFlagPeriod10Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod11 {
            get {
                return this.cbPrevDatePeriod11Field;
            }
            set {
                this.cbPrevDatePeriod11Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod11 {
            get {
                return this.cbPrevFlagPeriod11Field;
            }
            set {
                this.cbPrevFlagPeriod11Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevDatePeriod12 {
            get {
                return this.cbPrevDatePeriod12Field;
            }
            set {
                this.cbPrevDatePeriod12Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod12 {
            get {
                return this.cbPrevFlagPeriod12Field;
            }
            set {
                this.cbPrevFlagPeriod12Field = value;
            }
        }
        
        /// <remarks/>
        public CbPrevDatePeriod13 CbPrevDatePeriod13 {
            get {
                return this.cbPrevDatePeriod13Field;
            }
            set {
                this.cbPrevDatePeriod13Field = value;
            }
        }
        
        /// <remarks/>
        public string CbPrevFlagPeriod13 {
            get {
                return this.cbPrevFlagPeriod13Field;
            }
            set {
                this.cbPrevFlagPeriod13Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CbPrevDatePeriod13 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeriodCurrentYearType {
        
        private string cbCurrDatePeriod1Field;
        
        private string cbCurrFlagPeriod1Field;
        
        private string cbCurrDatePeriod2Field;
        
        private string cbCurrFlagPeriod2Field;
        
        private string cbCurrDatePeriod3Field;
        
        private string cbCurrFlagPeriod3Field;
        
        private string cbCurrDatePeriod4Field;
        
        private string cbCurrFlagPeriod4Field;
        
        private string cbCurrDatePeriod5Field;
        
        private string cbCurrFlagPeriod5Field;
        
        private string cbCurrDatePeriod6Field;
        
        private string cbCurrFlagPeriod6Field;
        
        private string cbCurrDatePeriod7Field;
        
        private string cbCurrFlagPeriod7Field;
        
        private string cbCurrDatePeriod8Field;
        
        private string cbCurrFlagPeriod8Field;
        
        private string cbCurrDatePeriod9Field;
        
        private string cbCurrFlagPeriod9Field;
        
        private string cbCurrDatePeriod10Field;
        
        private string cbCurrFlagPeriod10Field;
        
        private string cbCurrDatePeriod11Field;
        
        private string cbCurrFlagPeriod11Field;
        
        private string cbCurrDatePeriod12Field;
        
        private string cbCurrFlagPeriod12Field;
        
        private CbCurrDatePeriod13 cbCurrDatePeriod13Field;
        
        private string cbCurrFlagPeriod13Field;
        
        /// <remarks/>
        public string CbCurrDatePeriod1 {
            get {
                return this.cbCurrDatePeriod1Field;
            }
            set {
                this.cbCurrDatePeriod1Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod1 {
            get {
                return this.cbCurrFlagPeriod1Field;
            }
            set {
                this.cbCurrFlagPeriod1Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod2 {
            get {
                return this.cbCurrDatePeriod2Field;
            }
            set {
                this.cbCurrDatePeriod2Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod2 {
            get {
                return this.cbCurrFlagPeriod2Field;
            }
            set {
                this.cbCurrFlagPeriod2Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod3 {
            get {
                return this.cbCurrDatePeriod3Field;
            }
            set {
                this.cbCurrDatePeriod3Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod3 {
            get {
                return this.cbCurrFlagPeriod3Field;
            }
            set {
                this.cbCurrFlagPeriod3Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod4 {
            get {
                return this.cbCurrDatePeriod4Field;
            }
            set {
                this.cbCurrDatePeriod4Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod4 {
            get {
                return this.cbCurrFlagPeriod4Field;
            }
            set {
                this.cbCurrFlagPeriod4Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod5 {
            get {
                return this.cbCurrDatePeriod5Field;
            }
            set {
                this.cbCurrDatePeriod5Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod5 {
            get {
                return this.cbCurrFlagPeriod5Field;
            }
            set {
                this.cbCurrFlagPeriod5Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod6 {
            get {
                return this.cbCurrDatePeriod6Field;
            }
            set {
                this.cbCurrDatePeriod6Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod6 {
            get {
                return this.cbCurrFlagPeriod6Field;
            }
            set {
                this.cbCurrFlagPeriod6Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod7 {
            get {
                return this.cbCurrDatePeriod7Field;
            }
            set {
                this.cbCurrDatePeriod7Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod7 {
            get {
                return this.cbCurrFlagPeriod7Field;
            }
            set {
                this.cbCurrFlagPeriod7Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod8 {
            get {
                return this.cbCurrDatePeriod8Field;
            }
            set {
                this.cbCurrDatePeriod8Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod8 {
            get {
                return this.cbCurrFlagPeriod8Field;
            }
            set {
                this.cbCurrFlagPeriod8Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod9 {
            get {
                return this.cbCurrDatePeriod9Field;
            }
            set {
                this.cbCurrDatePeriod9Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod9 {
            get {
                return this.cbCurrFlagPeriod9Field;
            }
            set {
                this.cbCurrFlagPeriod9Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod10 {
            get {
                return this.cbCurrDatePeriod10Field;
            }
            set {
                this.cbCurrDatePeriod10Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod10 {
            get {
                return this.cbCurrFlagPeriod10Field;
            }
            set {
                this.cbCurrFlagPeriod10Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod11 {
            get {
                return this.cbCurrDatePeriod11Field;
            }
            set {
                this.cbCurrDatePeriod11Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod11 {
            get {
                return this.cbCurrFlagPeriod11Field;
            }
            set {
                this.cbCurrFlagPeriod11Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrDatePeriod12 {
            get {
                return this.cbCurrDatePeriod12Field;
            }
            set {
                this.cbCurrDatePeriod12Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod12 {
            get {
                return this.cbCurrFlagPeriod12Field;
            }
            set {
                this.cbCurrFlagPeriod12Field = value;
            }
        }
        
        /// <remarks/>
        public CbCurrDatePeriod13 CbCurrDatePeriod13 {
            get {
                return this.cbCurrDatePeriod13Field;
            }
            set {
                this.cbCurrDatePeriod13Field = value;
            }
        }
        
        /// <remarks/>
        public string CbCurrFlagPeriod13 {
            get {
                return this.cbCurrFlagPeriod13Field;
            }
            set {
                this.cbCurrFlagPeriod13Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CbCurrDatePeriod13 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaxType {
        
        private string taxDistrMethodField;
        
        private string taxDistrReqForField;
        
        private string defTaxCodeCshDepField;
        
        private string defTaxCodeCshWithField;
        
        /// <remarks/>
        public string TaxDistrMethod {
            get {
                return this.taxDistrMethodField;
            }
            set {
                this.taxDistrMethodField = value;
            }
        }
        
        /// <remarks/>
        public string TaxDistrReqFor {
            get {
                return this.taxDistrReqForField;
            }
            set {
                this.taxDistrReqForField = value;
            }
        }
        
        /// <remarks/>
        public string DefTaxCodeCshDep {
            get {
                return this.defTaxCodeCshDepField;
            }
            set {
                this.defTaxCodeCshDepField = value;
            }
        }
        
        /// <remarks/>
        public string DefTaxCodeCshWith {
            get {
                return this.defTaxCodeCshWithField;
            }
            set {
                this.defTaxCodeCshWithField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HistoryType {
        
        private sbyte mthsRetCbJnlsField;
        
        private sbyte mthsRetReconTransField;
        
        /// <remarks/>
        public sbyte MthsRetCbJnls {
            get {
                return this.mthsRetCbJnlsField;
            }
            set {
                this.mthsRetCbJnlsField = value;
            }
        }
        
        /// <remarks/>
        public sbyte MthsRetReconTrans {
            get {
                return this.mthsRetReconTransField;
            }
            set {
                this.mthsRetReconTransField = value;
            }
        }
    }
}
