//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SYSPRO.NET.BusinessObjects.inv_goods_in_transit_trial_balance_out {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GITTrialBalance {
        
        private GITTrialBalanceSystemInformation systemInformationField;
        
        private GITTrialBalanceQueryOptions queryOptionsField;
        
        private GITTrialBalanceWarehouseItem[] warehousesField;
        
        private GITTrialBalanceReportTotals reportTotalsField;
        
        private GITTrialBalanceGitControlAccountItem[] gITControlAccountsField;
        
        /// <remarks/>
        public GITTrialBalanceSystemInformation SystemInformation {
            get {
                return this.systemInformationField;
            }
            set {
                this.systemInformationField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceQueryOptions QueryOptions {
            get {
                return this.queryOptionsField;
            }
            set {
                this.queryOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("WarehouseItem", IsNullable=false)]
        public GITTrialBalanceWarehouseItem[] Warehouses {
            get {
                return this.warehousesField;
            }
            set {
                this.warehousesField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceReportTotals ReportTotals {
            get {
                return this.reportTotalsField;
            }
            set {
                this.reportTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("GitControlAccountItem", IsNullable=false)]
        public GITTrialBalanceGitControlAccountItem[] GITControlAccounts {
            get {
                return this.gITControlAccountsField;
            }
            set {
                this.gITControlAccountsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceSystemInformation {
        
        private string cssStyleField;
        
        private string languageField;
        
        private string decFormatField;
        
        private string dateFormatField;
        
        private string versionField;
        
        private string companyIdField;
        
        private string companyNameField;
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string operatorGroupField;
        
        private string operatorEmailAddressField;
        
        private string operatorLocationField;
        
        private string reportDateField;
        
        private string useSeparatorOnReportsField;
        
        private string separatorToUseField;
        
        private double noOfDigitsField;
        
        private bool noOfDigitsFieldSpecified;
        
        private string decCharToUseField;
        
        /// <remarks/>
        public string CssStyle {
            get {
                return this.cssStyleField;
            }
            set {
                this.cssStyleField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string DecFormat {
            get {
                return this.decFormatField;
            }
            set {
                this.decFormatField = value;
            }
        }
        
        /// <remarks/>
        public string DateFormat {
            get {
                return this.dateFormatField;
            }
            set {
                this.dateFormatField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorGroup {
            get {
                return this.operatorGroupField;
            }
            set {
                this.operatorGroupField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorEmailAddress {
            get {
                return this.operatorEmailAddressField;
            }
            set {
                this.operatorEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorLocation {
            get {
                return this.operatorLocationField;
            }
            set {
                this.operatorLocationField = value;
            }
        }
        
        /// <remarks/>
        public string ReportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
        
        /// <remarks/>
        public string UseSeparatorOnReports {
            get {
                return this.useSeparatorOnReportsField;
            }
            set {
                this.useSeparatorOnReportsField = value;
            }
        }
        
        /// <remarks/>
        public string SeparatorToUse {
            get {
                return this.separatorToUseField;
            }
            set {
                this.separatorToUseField = value;
            }
        }
        
        /// <remarks/>
        public double NoOfDigits {
            get {
                return this.noOfDigitsField;
            }
            set {
                this.noOfDigitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfDigitsSpecified {
            get {
                return this.noOfDigitsFieldSpecified;
            }
            set {
                this.noOfDigitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DecCharToUse {
            get {
                return this.decCharToUseField;
            }
            set {
                this.decCharToUseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceQueryOptions {
        
        private string sequenceField;
        
        private string translated_SequenceField;
        
        private string trialBalanceAsOfField;
        
        private string translated_TrialBalanceAsOfField;
        
        private string reportTypeField;
        
        private string translated_ReportTypeField;
        
        private string includeCompletedGitField;
        
        private string translated_IncludeCompletedGitField;
        
        private string stockCodeFilterTypeField;
        
        private string translated_StockCodeFilterTypeField;
        
        private string stockCodeFilterValueField;
        
        private string productClassFilterTypeField;
        
        private string translated_ProductClassFilterTypeField;
        
        private string productClassFilterValueField;
        
        private string sourceWarehouseFilterTypeField;
        
        private string translated_SourceWarehouseFilterTypeField;
        
        private string sourceWarehouseFilterValueField;
        
        private string targetWarehouseFilterTypeField;
        
        private string translated_TargetWarehouseFilterTypeField;
        
        private string targetWarehouseFilterValueField;
        
        private string currentYearField;
        
        private string currentPeriodField;
        
        private object selectedYearField;
        
        private object selectedPeriodField;
        
        private string translated_Group1HeadingField;
        
        /// <remarks/>
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_Sequence {
            get {
                return this.translated_SequenceField;
            }
            set {
                this.translated_SequenceField = value;
            }
        }
        
        /// <remarks/>
        public string TrialBalanceAsOf {
            get {
                return this.trialBalanceAsOfField;
            }
            set {
                this.trialBalanceAsOfField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_TrialBalanceAsOf {
            get {
                return this.translated_TrialBalanceAsOfField;
            }
            set {
                this.translated_TrialBalanceAsOfField = value;
            }
        }
        
        /// <remarks/>
        public string ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_ReportType {
            get {
                return this.translated_ReportTypeField;
            }
            set {
                this.translated_ReportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IncludeCompletedGit {
            get {
                return this.includeCompletedGitField;
            }
            set {
                this.includeCompletedGitField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_IncludeCompletedGit {
            get {
                return this.translated_IncludeCompletedGitField;
            }
            set {
                this.translated_IncludeCompletedGitField = value;
            }
        }
        
        /// <remarks/>
        public string StockCodeFilterType {
            get {
                return this.stockCodeFilterTypeField;
            }
            set {
                this.stockCodeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_StockCodeFilterType {
            get {
                return this.translated_StockCodeFilterTypeField;
            }
            set {
                this.translated_StockCodeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StockCodeFilterValue {
            get {
                return this.stockCodeFilterValueField;
            }
            set {
                this.stockCodeFilterValueField = value;
            }
        }
        
        /// <remarks/>
        public string ProductClassFilterType {
            get {
                return this.productClassFilterTypeField;
            }
            set {
                this.productClassFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_ProductClassFilterType {
            get {
                return this.translated_ProductClassFilterTypeField;
            }
            set {
                this.translated_ProductClassFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductClassFilterValue {
            get {
                return this.productClassFilterValueField;
            }
            set {
                this.productClassFilterValueField = value;
            }
        }
        
        /// <remarks/>
        public string SourceWarehouseFilterType {
            get {
                return this.sourceWarehouseFilterTypeField;
            }
            set {
                this.sourceWarehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_SourceWarehouseFilterType {
            get {
                return this.translated_SourceWarehouseFilterTypeField;
            }
            set {
                this.translated_SourceWarehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceWarehouseFilterValue {
            get {
                return this.sourceWarehouseFilterValueField;
            }
            set {
                this.sourceWarehouseFilterValueField = value;
            }
        }
        
        /// <remarks/>
        public string TargetWarehouseFilterType {
            get {
                return this.targetWarehouseFilterTypeField;
            }
            set {
                this.targetWarehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_TargetWarehouseFilterType {
            get {
                return this.translated_TargetWarehouseFilterTypeField;
            }
            set {
                this.translated_TargetWarehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TargetWarehouseFilterValue {
            get {
                return this.targetWarehouseFilterValueField;
            }
            set {
                this.targetWarehouseFilterValueField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentYear {
            get {
                return this.currentYearField;
            }
            set {
                this.currentYearField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentPeriod {
            get {
                return this.currentPeriodField;
            }
            set {
                this.currentPeriodField = value;
            }
        }
        
        /// <remarks/>
        public object SelectedYear {
            get {
                return this.selectedYearField;
            }
            set {
                this.selectedYearField = value;
            }
        }
        
        /// <remarks/>
        public object SelectedPeriod {
            get {
                return this.selectedPeriodField;
            }
            set {
                this.selectedPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string Translated_Group1Heading {
            get {
                return this.translated_Group1HeadingField;
            }
            set {
                this.translated_Group1HeadingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItem {
        
        private string warehouseField;
        
        private string editedWarehouseField;
        
        private string warehouseDescField;
        
        private string whSourceTargetField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItem[] detailWarehousesField;
        
        private GITTrialBalanceWarehouseItemWarehouseTotals warehouseTotalsField;
        
        /// <remarks/>
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouse {
            get {
                return this.editedWarehouseField;
            }
            set {
                this.editedWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string WarehouseDesc {
            get {
                return this.warehouseDescField;
            }
            set {
                this.warehouseDescField = value;
            }
        }
        
        /// <remarks/>
        public string WhSourceTarget {
            get {
                return this.whSourceTargetField;
            }
            set {
                this.whSourceTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DetailWarehouseItem", IsNullable=false)]
        public GITTrialBalanceWarehouseItemDetailWarehouseItem[] DetailWarehouses {
            get {
                return this.detailWarehousesField;
            }
            set {
                this.detailWarehousesField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceWarehouseItemWarehouseTotals WarehouseTotals {
            get {
                return this.warehouseTotalsField;
            }
            set {
                this.warehouseTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemDetailWarehouseItem {
        
        private string detailWarehouseField;
        
        private string editedDetailWarehouseField;
        
        private string detailWarehouseDescField;
        
        private string detailWhSourceTargetField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItem[] stockCodesField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItemDetailWhTotals detailWhTotalsField;
        
        /// <remarks/>
        public string DetailWarehouse {
            get {
                return this.detailWarehouseField;
            }
            set {
                this.detailWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWarehouse {
            get {
                return this.editedDetailWarehouseField;
            }
            set {
                this.editedDetailWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string DetailWarehouseDesc {
            get {
                return this.detailWarehouseDescField;
            }
            set {
                this.detailWarehouseDescField = value;
            }
        }
        
        /// <remarks/>
        public string DetailWhSourceTarget {
            get {
                return this.detailWhSourceTargetField;
            }
            set {
                this.detailWhSourceTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StockCodeItem", IsNullable=false)]
        public GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItem[] StockCodes {
            get {
                return this.stockCodesField;
            }
            set {
                this.stockCodesField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceWarehouseItemDetailWarehouseItemDetailWhTotals DetailWhTotals {
            get {
                return this.detailWhTotalsField;
            }
            set {
                this.detailWhTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItem {
        
        private string stockCodeField;
        
        private string stockCodeDescField;
        
        private string productClassField;
        
        private string productClassDescField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItem[] transactionsField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemStockCodeTotal stockCodeTotalField;
        
        /// <remarks/>
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StockCodeDesc {
            get {
                return this.stockCodeDescField;
            }
            set {
                this.stockCodeDescField = value;
            }
        }
        
        /// <remarks/>
        public string ProductClass {
            get {
                return this.productClassField;
            }
            set {
                this.productClassField = value;
            }
        }
        
        /// <remarks/>
        public string ProductClassDesc {
            get {
                return this.productClassDescField;
            }
            set {
                this.productClassDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TransactionItem", IsNullable=false)]
        public GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItem[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemStockCodeTotal StockCodeTotal {
            get {
                return this.stockCodeTotalField;
            }
            set {
                this.stockCodeTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItem {
        
        private string dateCreatedField;
        
        private string controlAccountField;
        
        private GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItemEntryType entryTypeField;
        
        private bool entryTypeFieldSpecified;
        
        private string editedEntryTypeField;
        
        private string gtrReferenceField;
        
        private double gtrTransferValueField;
        
        private bool gtrTransferValueFieldSpecified;
        
        private string editedGtrTransferValueField;
        
        private double gtrReceivedValueField;
        
        private bool gtrReceivedValueFieldSpecified;
        
        private string editedGtrReceivedValueField;
        
        private double gtrAdjustedToSourceValueField;
        
        private bool gtrAdjustedToSourceValueFieldSpecified;
        
        private string editedGtrAdjustedToSourceValueField;
        
        private double gtrInTransitValueField;
        
        private bool gtrInTransitValueFieldSpecified;
        
        private string editedGtrInTransitValueField;
        
        private double gtrCompVarianceValueField;
        
        private bool gtrCompVarianceValueFieldSpecified;
        
        private string editedGtrCompVarianceValueField;
        
        /// <remarks/>
        public string DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string ControlAccount {
            get {
                return this.controlAccountField;
            }
            set {
                this.controlAccountField = value;
            }
        }
        
        /// <remarks/>
        public GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItemEntryType EntryType {
            get {
                return this.entryTypeField;
            }
            set {
                this.entryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryTypeSpecified {
            get {
                return this.entryTypeFieldSpecified;
            }
            set {
                this.entryTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedEntryType {
            get {
                return this.editedEntryTypeField;
            }
            set {
                this.editedEntryTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GtrReference {
            get {
                return this.gtrReferenceField;
            }
            set {
                this.gtrReferenceField = value;
            }
        }
        
        /// <remarks/>
        public double GtrTransferValue {
            get {
                return this.gtrTransferValueField;
            }
            set {
                this.gtrTransferValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GtrTransferValueSpecified {
            get {
                return this.gtrTransferValueFieldSpecified;
            }
            set {
                this.gtrTransferValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedGtrTransferValue {
            get {
                return this.editedGtrTransferValueField;
            }
            set {
                this.editedGtrTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public double GtrReceivedValue {
            get {
                return this.gtrReceivedValueField;
            }
            set {
                this.gtrReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GtrReceivedValueSpecified {
            get {
                return this.gtrReceivedValueFieldSpecified;
            }
            set {
                this.gtrReceivedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedGtrReceivedValue {
            get {
                return this.editedGtrReceivedValueField;
            }
            set {
                this.editedGtrReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public double GtrAdjustedToSourceValue {
            get {
                return this.gtrAdjustedToSourceValueField;
            }
            set {
                this.gtrAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GtrAdjustedToSourceValueSpecified {
            get {
                return this.gtrAdjustedToSourceValueFieldSpecified;
            }
            set {
                this.gtrAdjustedToSourceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedGtrAdjustedToSourceValue {
            get {
                return this.editedGtrAdjustedToSourceValueField;
            }
            set {
                this.editedGtrAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public double GtrInTransitValue {
            get {
                return this.gtrInTransitValueField;
            }
            set {
                this.gtrInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GtrInTransitValueSpecified {
            get {
                return this.gtrInTransitValueFieldSpecified;
            }
            set {
                this.gtrInTransitValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedGtrInTransitValue {
            get {
                return this.editedGtrInTransitValueField;
            }
            set {
                this.editedGtrInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public double GtrCompVarianceValue {
            get {
                return this.gtrCompVarianceValueField;
            }
            set {
                this.gtrCompVarianceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GtrCompVarianceValueSpecified {
            get {
                return this.gtrCompVarianceValueFieldSpecified;
            }
            set {
                this.gtrCompVarianceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedGtrCompVarianceValue {
            get {
                return this.editedGtrCompVarianceValueField;
            }
            set {
                this.editedGtrCompVarianceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemTransactionItemEntryType {
        
        /// <remarks/>
        SCT,
        
        /// <remarks/>
        IWT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemDetailWarehouseItemStockCodeItemStockCodeTotal {
        
        private double stkTotalTransferValueField;
        
        private bool stkTotalTransferValueFieldSpecified;
        
        private string editedStkTotalTransferValueField;
        
        private double stkTotalReceivedValueField;
        
        private bool stkTotalReceivedValueFieldSpecified;
        
        private string editedStkTotalReceivedValueField;
        
        private double stkTotalAdjustedToSourceValueField;
        
        private bool stkTotalAdjustedToSourceValueFieldSpecified;
        
        private string editedStkTotalAdjustedToSourceValueField;
        
        private double stkTotalInTransitValueField;
        
        private bool stkTotalInTransitValueFieldSpecified;
        
        private string editedStkTotalInTransitValueField;
        
        private double stkTotalCompVarianceValueField;
        
        private bool stkTotalCompVarianceValueFieldSpecified;
        
        private string editedStkTotalCompVarianceValueField;
        
        /// <remarks/>
        public double StkTotalTransferValue {
            get {
                return this.stkTotalTransferValueField;
            }
            set {
                this.stkTotalTransferValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StkTotalTransferValueSpecified {
            get {
                return this.stkTotalTransferValueFieldSpecified;
            }
            set {
                this.stkTotalTransferValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedStkTotalTransferValue {
            get {
                return this.editedStkTotalTransferValueField;
            }
            set {
                this.editedStkTotalTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public double StkTotalReceivedValue {
            get {
                return this.stkTotalReceivedValueField;
            }
            set {
                this.stkTotalReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StkTotalReceivedValueSpecified {
            get {
                return this.stkTotalReceivedValueFieldSpecified;
            }
            set {
                this.stkTotalReceivedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedStkTotalReceivedValue {
            get {
                return this.editedStkTotalReceivedValueField;
            }
            set {
                this.editedStkTotalReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public double StkTotalAdjustedToSourceValue {
            get {
                return this.stkTotalAdjustedToSourceValueField;
            }
            set {
                this.stkTotalAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StkTotalAdjustedToSourceValueSpecified {
            get {
                return this.stkTotalAdjustedToSourceValueFieldSpecified;
            }
            set {
                this.stkTotalAdjustedToSourceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedStkTotalAdjustedToSourceValue {
            get {
                return this.editedStkTotalAdjustedToSourceValueField;
            }
            set {
                this.editedStkTotalAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public double StkTotalInTransitValue {
            get {
                return this.stkTotalInTransitValueField;
            }
            set {
                this.stkTotalInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StkTotalInTransitValueSpecified {
            get {
                return this.stkTotalInTransitValueFieldSpecified;
            }
            set {
                this.stkTotalInTransitValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedStkTotalInTransitValue {
            get {
                return this.editedStkTotalInTransitValueField;
            }
            set {
                this.editedStkTotalInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public double StkTotalCompVarianceValue {
            get {
                return this.stkTotalCompVarianceValueField;
            }
            set {
                this.stkTotalCompVarianceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StkTotalCompVarianceValueSpecified {
            get {
                return this.stkTotalCompVarianceValueFieldSpecified;
            }
            set {
                this.stkTotalCompVarianceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedStkTotalCompVarianceValue {
            get {
                return this.editedStkTotalCompVarianceValueField;
            }
            set {
                this.editedStkTotalCompVarianceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemDetailWarehouseItemDetailWhTotals {
        
        private double detailWhTransferValueField;
        
        private bool detailWhTransferValueFieldSpecified;
        
        private string editedDetailWhTransferValueField;
        
        private double detailWhReceivedValueField;
        
        private bool detailWhReceivedValueFieldSpecified;
        
        private string editedDetailWhReceivedValueField;
        
        private double detailWhAdjustedToSourceValueField;
        
        private bool detailWhAdjustedToSourceValueFieldSpecified;
        
        private string editedDetailWhAdjustedToSourceValueField;
        
        private double detailWhInTransitValueField;
        
        private bool detailWhInTransitValueFieldSpecified;
        
        private string editedDetailWhInTransitValueField;
        
        private double detailWhCompVarianceValueField;
        
        private bool detailWhCompVarianceValueFieldSpecified;
        
        private string editedDetailWhCompVarianceValueField;
        
        /// <remarks/>
        public double DetailWhTransferValue {
            get {
                return this.detailWhTransferValueField;
            }
            set {
                this.detailWhTransferValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailWhTransferValueSpecified {
            get {
                return this.detailWhTransferValueFieldSpecified;
            }
            set {
                this.detailWhTransferValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWhTransferValue {
            get {
                return this.editedDetailWhTransferValueField;
            }
            set {
                this.editedDetailWhTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public double DetailWhReceivedValue {
            get {
                return this.detailWhReceivedValueField;
            }
            set {
                this.detailWhReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailWhReceivedValueSpecified {
            get {
                return this.detailWhReceivedValueFieldSpecified;
            }
            set {
                this.detailWhReceivedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWhReceivedValue {
            get {
                return this.editedDetailWhReceivedValueField;
            }
            set {
                this.editedDetailWhReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public double DetailWhAdjustedToSourceValue {
            get {
                return this.detailWhAdjustedToSourceValueField;
            }
            set {
                this.detailWhAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailWhAdjustedToSourceValueSpecified {
            get {
                return this.detailWhAdjustedToSourceValueFieldSpecified;
            }
            set {
                this.detailWhAdjustedToSourceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWhAdjustedToSourceValue {
            get {
                return this.editedDetailWhAdjustedToSourceValueField;
            }
            set {
                this.editedDetailWhAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public double DetailWhInTransitValue {
            get {
                return this.detailWhInTransitValueField;
            }
            set {
                this.detailWhInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailWhInTransitValueSpecified {
            get {
                return this.detailWhInTransitValueFieldSpecified;
            }
            set {
                this.detailWhInTransitValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWhInTransitValue {
            get {
                return this.editedDetailWhInTransitValueField;
            }
            set {
                this.editedDetailWhInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public double DetailWhCompVarianceValue {
            get {
                return this.detailWhCompVarianceValueField;
            }
            set {
                this.detailWhCompVarianceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailWhCompVarianceValueSpecified {
            get {
                return this.detailWhCompVarianceValueFieldSpecified;
            }
            set {
                this.detailWhCompVarianceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedDetailWhCompVarianceValue {
            get {
                return this.editedDetailWhCompVarianceValueField;
            }
            set {
                this.editedDetailWhCompVarianceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceWarehouseItemWarehouseTotals {
        
        private double warehouseTransferValueField;
        
        private string editedWarehouseTransferValueField;
        
        private double warehouseReceivedValueField;
        
        private string editedWarehouseReceivedValueField;
        
        private double warehouseAdjustedToSourceValueField;
        
        private string editedWarehouseAdjustedToSourceValueField;
        
        private double warehouseInTransitValueField;
        
        private string editedWarehouseInTransitValueField;
        
        private double warehouseCompVarianceValueField;
        
        private string editedWarehouseCompVarianceValueField;
        
        /// <remarks/>
        public double WarehouseTransferValue {
            get {
                return this.warehouseTransferValueField;
            }
            set {
                this.warehouseTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouseTransferValue {
            get {
                return this.editedWarehouseTransferValueField;
            }
            set {
                this.editedWarehouseTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public double WarehouseReceivedValue {
            get {
                return this.warehouseReceivedValueField;
            }
            set {
                this.warehouseReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouseReceivedValue {
            get {
                return this.editedWarehouseReceivedValueField;
            }
            set {
                this.editedWarehouseReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public double WarehouseAdjustedToSourceValue {
            get {
                return this.warehouseAdjustedToSourceValueField;
            }
            set {
                this.warehouseAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouseAdjustedToSourceValue {
            get {
                return this.editedWarehouseAdjustedToSourceValueField;
            }
            set {
                this.editedWarehouseAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public double WarehouseInTransitValue {
            get {
                return this.warehouseInTransitValueField;
            }
            set {
                this.warehouseInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouseInTransitValue {
            get {
                return this.editedWarehouseInTransitValueField;
            }
            set {
                this.editedWarehouseInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public double WarehouseCompVarianceValue {
            get {
                return this.warehouseCompVarianceValueField;
            }
            set {
                this.warehouseCompVarianceValueField = value;
            }
        }
        
        /// <remarks/>
        public string EditedWarehouseCompVarianceValue {
            get {
                return this.editedWarehouseCompVarianceValueField;
            }
            set {
                this.editedWarehouseCompVarianceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceReportTotals {
        
        private double totalTransferValueField;
        
        private bool totalTransferValueFieldSpecified;
        
        private string editedTotalTransferValueField;
        
        private double totalReceivedValueField;
        
        private bool totalReceivedValueFieldSpecified;
        
        private string editedTotalReceivedValueField;
        
        private double totalAdjustedToSourceValueField;
        
        private bool totalAdjustedToSourceValueFieldSpecified;
        
        private string editedTotalAdjustedToSourceValueField;
        
        private double totalInTransitValueField;
        
        private bool totalInTransitValueFieldSpecified;
        
        private string editedTotalInTransitValueField;
        
        private double totalWhCompVarianceValueField;
        
        private bool totalWhCompVarianceValueFieldSpecified;
        
        private string editedTotalWhCompVarianceValueField;
        
        /// <remarks/>
        public double TotalTransferValue {
            get {
                return this.totalTransferValueField;
            }
            set {
                this.totalTransferValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalTransferValueSpecified {
            get {
                return this.totalTransferValueFieldSpecified;
            }
            set {
                this.totalTransferValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalTransferValue {
            get {
                return this.editedTotalTransferValueField;
            }
            set {
                this.editedTotalTransferValueField = value;
            }
        }
        
        /// <remarks/>
        public double TotalReceivedValue {
            get {
                return this.totalReceivedValueField;
            }
            set {
                this.totalReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalReceivedValueSpecified {
            get {
                return this.totalReceivedValueFieldSpecified;
            }
            set {
                this.totalReceivedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalReceivedValue {
            get {
                return this.editedTotalReceivedValueField;
            }
            set {
                this.editedTotalReceivedValueField = value;
            }
        }
        
        /// <remarks/>
        public double TotalAdjustedToSourceValue {
            get {
                return this.totalAdjustedToSourceValueField;
            }
            set {
                this.totalAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdjustedToSourceValueSpecified {
            get {
                return this.totalAdjustedToSourceValueFieldSpecified;
            }
            set {
                this.totalAdjustedToSourceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalAdjustedToSourceValue {
            get {
                return this.editedTotalAdjustedToSourceValueField;
            }
            set {
                this.editedTotalAdjustedToSourceValueField = value;
            }
        }
        
        /// <remarks/>
        public double TotalInTransitValue {
            get {
                return this.totalInTransitValueField;
            }
            set {
                this.totalInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalInTransitValueSpecified {
            get {
                return this.totalInTransitValueFieldSpecified;
            }
            set {
                this.totalInTransitValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalInTransitValue {
            get {
                return this.editedTotalInTransitValueField;
            }
            set {
                this.editedTotalInTransitValueField = value;
            }
        }
        
        /// <remarks/>
        public double TotalWhCompVarianceValue {
            get {
                return this.totalWhCompVarianceValueField;
            }
            set {
                this.totalWhCompVarianceValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalWhCompVarianceValueSpecified {
            get {
                return this.totalWhCompVarianceValueFieldSpecified;
            }
            set {
                this.totalWhCompVarianceValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalWhCompVarianceValue {
            get {
                return this.editedTotalWhCompVarianceValueField;
            }
            set {
                this.editedTotalWhCompVarianceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GITTrialBalanceGitControlAccountItem {
        
        private string gitControlAccountField;
        
        private string controlAccountDescriptionField;
        
        private double totalAmountField;
        
        private bool totalAmountFieldSpecified;
        
        private string editedTotalAmountField;
        
        /// <remarks/>
        public string GitControlAccount {
            get {
                return this.gitControlAccountField;
            }
            set {
                this.gitControlAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ControlAccountDescription {
            get {
                return this.controlAccountDescriptionField;
            }
            set {
                this.controlAccountDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountSpecified {
            get {
                return this.totalAmountFieldSpecified;
            }
            set {
                this.totalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EditedTotalAmount {
            get {
                return this.editedTotalAmountField;
            }
            set {
                this.editedTotalAmountField = value;
            }
        }
    }
}
