//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SYSPRO.NET.BusinessObjects.so_backlog_by_stock_code_out {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SOBacklogByStockCodeQuery {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BacklogItem", typeof(SOBacklogByStockCodeQueryBacklogItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("BacklogTotals", typeof(SOBacklogByStockCodeQueryBacklogTotals), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("QueryOptions", typeof(SOBacklogByStockCodeQueryQueryOptions), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SystemInformation", typeof(SOBacklogByStockCodeQuerySystemInformation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQueryBacklogItem {
        
        private string stockCodeField;
        
        private string translated_StockCodeField;
        
        private string descriptionField;
        
        private string unitOfMeasureField;
        
        private double decimalsField;
        
        private bool decimalsFieldSpecified;
        
        private string revisionField;
        
        private string releaseField;
        
        private string versionReleaseField;
        
        private string sequenceKeyField;
        
        private double quantityOnHandField;
        
        private bool quantityOnHandFieldSpecified;
        
        private string quantityOnHandUnitsField;
        
        private string editedQuantityOnHandField;
        
        private string translated_HandField;
        
        private double quantityAvailableField;
        
        private bool quantityAvailableFieldSpecified;
        
        private string quantityAvailableUnitsField;
        
        private string editedQuantityAvailableField;
        
        private string translated_AvaiField;
        
        private double freeStockField;
        
        private bool freeStockFieldSpecified;
        
        private string freeStockUnitsField;
        
        private string editedFreeStockField;
        
        private string translated_FreeField;
        
        private SOBacklogByStockCodeQueryBacklogItemOrderItemsOrderItem[][] orderItemsField;
        
        private SOBacklogByStockCodeQueryBacklogItemBacklogItemTotals[] backlogItemTotalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_StockCode {
            get {
                return this.translated_StockCodeField;
            }
            set {
                this.translated_StockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Decimals {
            get {
                return this.decimalsField;
            }
            set {
                this.decimalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DecimalsSpecified {
            get {
                return this.decimalsFieldSpecified;
            }
            set {
                this.decimalsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VersionRelease {
            get {
                return this.versionReleaseField;
            }
            set {
                this.versionReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SequenceKey {
            get {
                return this.sequenceKeyField;
            }
            set {
                this.sequenceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double QuantityOnHand {
            get {
                return this.quantityOnHandField;
            }
            set {
                this.quantityOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityOnHandSpecified {
            get {
                return this.quantityOnHandFieldSpecified;
            }
            set {
                this.quantityOnHandFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityOnHandUnits {
            get {
                return this.quantityOnHandUnitsField;
            }
            set {
                this.quantityOnHandUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedQuantityOnHand {
            get {
                return this.editedQuantityOnHandField;
            }
            set {
                this.editedQuantityOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_Hand {
            get {
                return this.translated_HandField;
            }
            set {
                this.translated_HandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double QuantityAvailable {
            get {
                return this.quantityAvailableField;
            }
            set {
                this.quantityAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityAvailableSpecified {
            get {
                return this.quantityAvailableFieldSpecified;
            }
            set {
                this.quantityAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityAvailableUnits {
            get {
                return this.quantityAvailableUnitsField;
            }
            set {
                this.quantityAvailableUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedQuantityAvailable {
            get {
                return this.editedQuantityAvailableField;
            }
            set {
                this.editedQuantityAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_Avai {
            get {
                return this.translated_AvaiField;
            }
            set {
                this.translated_AvaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double FreeStock {
            get {
                return this.freeStockField;
            }
            set {
                this.freeStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FreeStockSpecified {
            get {
                return this.freeStockFieldSpecified;
            }
            set {
                this.freeStockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FreeStockUnits {
            get {
                return this.freeStockUnitsField;
            }
            set {
                this.freeStockUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedFreeStock {
            get {
                return this.editedFreeStockField;
            }
            set {
                this.editedFreeStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_Free {
            get {
                return this.translated_FreeField;
            }
            set {
                this.translated_FreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderItem", typeof(SOBacklogByStockCodeQueryBacklogItemOrderItemsOrderItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SOBacklogByStockCodeQueryBacklogItemOrderItemsOrderItem[][] OrderItems {
            get {
                return this.orderItemsField;
            }
            set {
                this.orderItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BacklogItemTotals", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOBacklogByStockCodeQueryBacklogItemBacklogItemTotals[] BacklogItemTotals {
            get {
                return this.backlogItemTotalsField;
            }
            set {
                this.backlogItemTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQueryBacklogItemOrderItemsOrderItem {
        
        private string customerField;
        
        private string customerNameField;
        
        private string targetWarehouseField;
        
        private string targetWarehouseDescField;
        
        private string salesOrderField;
        
        private string salesOrderLineField;
        
        private string branchField;
        
        private string branchDescriptionField;
        
        private string warehouseField;
        
        private string warehouseDescriptionField;
        
        private string orderDateField;
        
        private string shipDateField;
        
        private double shipQuantityField;
        
        private bool shipQuantityFieldSpecified;
        
        private string shipQuantityUnitsField;
        
        private string editedShipQuantityField;
        
        private double reservedQuantityField;
        
        private bool reservedQuantityFieldSpecified;
        
        private string reservedQuantityUnitsField;
        
        private string editedReservedQuantityField;
        
        private double backOrderQuantityField;
        
        private bool backOrderQuantityFieldSpecified;
        
        private string backOrderQuantityUnitsField;
        
        private string editedBackOrderQuantityField;
        
        private string orderUomField;
        
        private string ageInDaysField;
        
        private string orderStatusField;
        
        private string orderStatusDescriptionField;
        
        private string customerPOField;
        
        private string scheduledField;
        
        private string parentPartField;
        
        private string translated_ParentPartField;
        
        private string componentPartField;
        
        private double shipValueField;
        
        private bool shipValueFieldSpecified;
        
        private string editedShipValueField;
        
        private double reservedValueField;
        
        private bool reservedValueFieldSpecified;
        
        private string editedReservedValueField;
        
        private double backOrderValueField;
        
        private bool backOrderValueFieldSpecified;
        
        private string editedBackOrderValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetWarehouse {
            get {
                return this.targetWarehouseField;
            }
            set {
                this.targetWarehouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetWarehouseDesc {
            get {
                return this.targetWarehouseDescField;
            }
            set {
                this.targetWarehouseDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesOrderLine {
            get {
                return this.salesOrderLineField;
            }
            set {
                this.salesOrderLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BranchDescription {
            get {
                return this.branchDescriptionField;
            }
            set {
                this.branchDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarehouseDescription {
            get {
                return this.warehouseDescriptionField;
            }
            set {
                this.warehouseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShipQuantity {
            get {
                return this.shipQuantityField;
            }
            set {
                this.shipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipQuantitySpecified {
            get {
                return this.shipQuantityFieldSpecified;
            }
            set {
                this.shipQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipQuantityUnits {
            get {
                return this.shipQuantityUnitsField;
            }
            set {
                this.shipQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedShipQuantity {
            get {
                return this.editedShipQuantityField;
            }
            set {
                this.editedShipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ReservedQuantity {
            get {
                return this.reservedQuantityField;
            }
            set {
                this.reservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservedQuantitySpecified {
            get {
                return this.reservedQuantityFieldSpecified;
            }
            set {
                this.reservedQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReservedQuantityUnits {
            get {
                return this.reservedQuantityUnitsField;
            }
            set {
                this.reservedQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedReservedQuantity {
            get {
                return this.editedReservedQuantityField;
            }
            set {
                this.editedReservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double BackOrderQuantity {
            get {
                return this.backOrderQuantityField;
            }
            set {
                this.backOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackOrderQuantitySpecified {
            get {
                return this.backOrderQuantityFieldSpecified;
            }
            set {
                this.backOrderQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BackOrderQuantityUnits {
            get {
                return this.backOrderQuantityUnitsField;
            }
            set {
                this.backOrderQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedBackOrderQuantity {
            get {
                return this.editedBackOrderQuantityField;
            }
            set {
                this.editedBackOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderUom {
            get {
                return this.orderUomField;
            }
            set {
                this.orderUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgeInDays {
            get {
                return this.ageInDaysField;
            }
            set {
                this.ageInDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderStatusDescription {
            get {
                return this.orderStatusDescriptionField;
            }
            set {
                this.orderStatusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPO {
            get {
                return this.customerPOField;
            }
            set {
                this.customerPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Scheduled {
            get {
                return this.scheduledField;
            }
            set {
                this.scheduledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentPart {
            get {
                return this.parentPartField;
            }
            set {
                this.parentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_ParentPart {
            get {
                return this.translated_ParentPartField;
            }
            set {
                this.translated_ParentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComponentPart {
            get {
                return this.componentPartField;
            }
            set {
                this.componentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShipValue {
            get {
                return this.shipValueField;
            }
            set {
                this.shipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipValueSpecified {
            get {
                return this.shipValueFieldSpecified;
            }
            set {
                this.shipValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedShipValue {
            get {
                return this.editedShipValueField;
            }
            set {
                this.editedShipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ReservedValue {
            get {
                return this.reservedValueField;
            }
            set {
                this.reservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservedValueSpecified {
            get {
                return this.reservedValueFieldSpecified;
            }
            set {
                this.reservedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedReservedValue {
            get {
                return this.editedReservedValueField;
            }
            set {
                this.editedReservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double BackOrderValue {
            get {
                return this.backOrderValueField;
            }
            set {
                this.backOrderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackOrderValueSpecified {
            get {
                return this.backOrderValueFieldSpecified;
            }
            set {
                this.backOrderValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedBackOrderValue {
            get {
                return this.editedBackOrderValueField;
            }
            set {
                this.editedBackOrderValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQueryBacklogItemBacklogItemTotals {
        
        private double itemTotalShipQuantityField;
        
        private bool itemTotalShipQuantityFieldSpecified;
        
        private string itemTotalShipQuantityUnitsField;
        
        private string editedItemTotalShipQuantityField;
        
        private double itemTotalReservedQuantityField;
        
        private bool itemTotalReservedQuantityFieldSpecified;
        
        private string itemTotalReservedQuantityUnitsField;
        
        private string editedItemTotalReservedQuantityField;
        
        private double itemTotalBackOrderQuantityField;
        
        private bool itemTotalBackOrderQuantityFieldSpecified;
        
        private string itemTotalBackOrderQuantityUnitsField;
        
        private string editedItemTotalBackOrderQuantityField;
        
        private double itemTotalShipValueField;
        
        private bool itemTotalShipValueFieldSpecified;
        
        private string editedItemTotalShipValueField;
        
        private double itemTotalReservedValueField;
        
        private bool itemTotalReservedValueFieldSpecified;
        
        private string editedItemTotalReservedValueField;
        
        private double itemTotalBackOrderValueField;
        
        private bool itemTotalBackOrderValueFieldSpecified;
        
        private string editedItemTotalBackOrderValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalShipQuantity {
            get {
                return this.itemTotalShipQuantityField;
            }
            set {
                this.itemTotalShipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalShipQuantitySpecified {
            get {
                return this.itemTotalShipQuantityFieldSpecified;
            }
            set {
                this.itemTotalShipQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemTotalShipQuantityUnits {
            get {
                return this.itemTotalShipQuantityUnitsField;
            }
            set {
                this.itemTotalShipQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalShipQuantity {
            get {
                return this.editedItemTotalShipQuantityField;
            }
            set {
                this.editedItemTotalShipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalReservedQuantity {
            get {
                return this.itemTotalReservedQuantityField;
            }
            set {
                this.itemTotalReservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalReservedQuantitySpecified {
            get {
                return this.itemTotalReservedQuantityFieldSpecified;
            }
            set {
                this.itemTotalReservedQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemTotalReservedQuantityUnits {
            get {
                return this.itemTotalReservedQuantityUnitsField;
            }
            set {
                this.itemTotalReservedQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalReservedQuantity {
            get {
                return this.editedItemTotalReservedQuantityField;
            }
            set {
                this.editedItemTotalReservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalBackOrderQuantity {
            get {
                return this.itemTotalBackOrderQuantityField;
            }
            set {
                this.itemTotalBackOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalBackOrderQuantitySpecified {
            get {
                return this.itemTotalBackOrderQuantityFieldSpecified;
            }
            set {
                this.itemTotalBackOrderQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemTotalBackOrderQuantityUnits {
            get {
                return this.itemTotalBackOrderQuantityUnitsField;
            }
            set {
                this.itemTotalBackOrderQuantityUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalBackOrderQuantity {
            get {
                return this.editedItemTotalBackOrderQuantityField;
            }
            set {
                this.editedItemTotalBackOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalShipValue {
            get {
                return this.itemTotalShipValueField;
            }
            set {
                this.itemTotalShipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalShipValueSpecified {
            get {
                return this.itemTotalShipValueFieldSpecified;
            }
            set {
                this.itemTotalShipValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalShipValue {
            get {
                return this.editedItemTotalShipValueField;
            }
            set {
                this.editedItemTotalShipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalReservedValue {
            get {
                return this.itemTotalReservedValueField;
            }
            set {
                this.itemTotalReservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalReservedValueSpecified {
            get {
                return this.itemTotalReservedValueFieldSpecified;
            }
            set {
                this.itemTotalReservedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalReservedValue {
            get {
                return this.editedItemTotalReservedValueField;
            }
            set {
                this.editedItemTotalReservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ItemTotalBackOrderValue {
            get {
                return this.itemTotalBackOrderValueField;
            }
            set {
                this.itemTotalBackOrderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemTotalBackOrderValueSpecified {
            get {
                return this.itemTotalBackOrderValueFieldSpecified;
            }
            set {
                this.itemTotalBackOrderValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedItemTotalBackOrderValue {
            get {
                return this.editedItemTotalBackOrderValueField;
            }
            set {
                this.editedItemTotalBackOrderValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQueryBacklogTotals {
        
        private double numberOfStockCodesField;
        
        private bool numberOfStockCodesFieldSpecified;
        
        private double totalOrderValueField;
        
        private bool totalOrderValueFieldSpecified;
        
        private string editedTotalOrderValueField;
        
        private double totalShipQuantityField;
        
        private bool totalShipQuantityFieldSpecified;
        
        private string editedTotalShipQuantityField;
        
        private double totalShipValueField;
        
        private bool totalShipValueFieldSpecified;
        
        private string editedTotalShipValueField;
        
        private double totalReservedQuantityField;
        
        private bool totalReservedQuantityFieldSpecified;
        
        private string editedTotalReservedQuantityField;
        
        private double totalReservedValueField;
        
        private bool totalReservedValueFieldSpecified;
        
        private string editedTotalReservedValueField;
        
        private double totalBackOrderQuantityField;
        
        private bool totalBackOrderQuantityFieldSpecified;
        
        private string editedTotalBackOrderQuantityField;
        
        private double totalBackOrderValueField;
        
        private bool totalBackOrderValueFieldSpecified;
        
        private string editedTotalBackOrderValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NumberOfStockCodes {
            get {
                return this.numberOfStockCodesField;
            }
            set {
                this.numberOfStockCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfStockCodesSpecified {
            get {
                return this.numberOfStockCodesFieldSpecified;
            }
            set {
                this.numberOfStockCodesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalOrderValue {
            get {
                return this.totalOrderValueField;
            }
            set {
                this.totalOrderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOrderValueSpecified {
            get {
                return this.totalOrderValueFieldSpecified;
            }
            set {
                this.totalOrderValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalOrderValue {
            get {
                return this.editedTotalOrderValueField;
            }
            set {
                this.editedTotalOrderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalShipQuantity {
            get {
                return this.totalShipQuantityField;
            }
            set {
                this.totalShipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalShipQuantitySpecified {
            get {
                return this.totalShipQuantityFieldSpecified;
            }
            set {
                this.totalShipQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalShipQuantity {
            get {
                return this.editedTotalShipQuantityField;
            }
            set {
                this.editedTotalShipQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalShipValue {
            get {
                return this.totalShipValueField;
            }
            set {
                this.totalShipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalShipValueSpecified {
            get {
                return this.totalShipValueFieldSpecified;
            }
            set {
                this.totalShipValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalShipValue {
            get {
                return this.editedTotalShipValueField;
            }
            set {
                this.editedTotalShipValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalReservedQuantity {
            get {
                return this.totalReservedQuantityField;
            }
            set {
                this.totalReservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalReservedQuantitySpecified {
            get {
                return this.totalReservedQuantityFieldSpecified;
            }
            set {
                this.totalReservedQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalReservedQuantity {
            get {
                return this.editedTotalReservedQuantityField;
            }
            set {
                this.editedTotalReservedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalReservedValue {
            get {
                return this.totalReservedValueField;
            }
            set {
                this.totalReservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalReservedValueSpecified {
            get {
                return this.totalReservedValueFieldSpecified;
            }
            set {
                this.totalReservedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalReservedValue {
            get {
                return this.editedTotalReservedValueField;
            }
            set {
                this.editedTotalReservedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalBackOrderQuantity {
            get {
                return this.totalBackOrderQuantityField;
            }
            set {
                this.totalBackOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBackOrderQuantitySpecified {
            get {
                return this.totalBackOrderQuantityFieldSpecified;
            }
            set {
                this.totalBackOrderQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalBackOrderQuantity {
            get {
                return this.editedTotalBackOrderQuantityField;
            }
            set {
                this.editedTotalBackOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalBackOrderValue {
            get {
                return this.totalBackOrderValueField;
            }
            set {
                this.totalBackOrderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBackOrderValueSpecified {
            get {
                return this.totalBackOrderValueFieldSpecified;
            }
            set {
                this.totalBackOrderValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditedTotalBackOrderValue {
            get {
                return this.editedTotalBackOrderValueField;
            }
            set {
                this.editedTotalBackOrderValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQueryQueryOptions {
        
        private string selectionField;
        
        private string translated_SelectionField;
        
        private string printOnlyIfStockOnHandField;
        
        private string translated_PrintOnlyIfStockOnHandField;
        
        private string printOnlyIfBackOrderQtyField;
        
        private string translated_PrintOnlyIfBackOrderQtyField;
        
        private string printCustomerPOField;
        
        private string translated_PrintCustomerPOField;
        
        private string printParentsOfKitsKorSField;
        
        private string translated_PrintParentsOfKitsKorSField;
        
        private string includeNonAllocSchedOrdersField;
        
        private string translated_IncludeNonAllocSchedOrdersField;
        
        private string includeNegBackOrderQtyField;
        
        private string translated_IncludeNegBackOrderQtyField;
        
        private string showValuesInField;
        
        private string translated_ShowValuesInField;
        
        private string revisionReleaseField;
        
        private string translated_RevRelField;
        
        private string stockCodeFilterTypeField;
        
        private string translated_StockCodeFilterTypeField;
        
        private string stockCodeFilterValueField;
        
        private string warehouseFilterTypeField;
        
        private string translated_WarehouseFilterTypeField;
        
        private string warehouseFilterValueField;
        
        private string translated_DateSelectionField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string translated_DateRangeField;
        
        private string productClassFilterTypeField;
        
        private string translated_ProductClassFilterTypeField;
        
        private string productClassFilterValueField;
        
        private string branchFilterTypeField;
        
        private string translated_BranchFilterTypeField;
        
        private string branchFilterValueField;
        
        private string orderTypeFilterTypeField;
        
        private string translated_OrderTypeFilterTypeField;
        
        private string orderTypeFilterValueField;
        
        private string currencyFilterTypeField;
        
        private string translated_CurrencyFilterTypeField;
        
        private string currencyFilterValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Selection {
            get {
                return this.selectionField;
            }
            set {
                this.selectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_Selection {
            get {
                return this.translated_SelectionField;
            }
            set {
                this.translated_SelectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrintOnlyIfStockOnHand {
            get {
                return this.printOnlyIfStockOnHandField;
            }
            set {
                this.printOnlyIfStockOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_PrintOnlyIfStockOnHand {
            get {
                return this.translated_PrintOnlyIfStockOnHandField;
            }
            set {
                this.translated_PrintOnlyIfStockOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrintOnlyIfBackOrderQty {
            get {
                return this.printOnlyIfBackOrderQtyField;
            }
            set {
                this.printOnlyIfBackOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_PrintOnlyIfBackOrderQty {
            get {
                return this.translated_PrintOnlyIfBackOrderQtyField;
            }
            set {
                this.translated_PrintOnlyIfBackOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrintCustomerPO {
            get {
                return this.printCustomerPOField;
            }
            set {
                this.printCustomerPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_PrintCustomerPO {
            get {
                return this.translated_PrintCustomerPOField;
            }
            set {
                this.translated_PrintCustomerPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrintParentsOfKitsKorS {
            get {
                return this.printParentsOfKitsKorSField;
            }
            set {
                this.printParentsOfKitsKorSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_PrintParentsOfKitsKorS {
            get {
                return this.translated_PrintParentsOfKitsKorSField;
            }
            set {
                this.translated_PrintParentsOfKitsKorSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IncludeNonAllocSchedOrders {
            get {
                return this.includeNonAllocSchedOrdersField;
            }
            set {
                this.includeNonAllocSchedOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_IncludeNonAllocSchedOrders {
            get {
                return this.translated_IncludeNonAllocSchedOrdersField;
            }
            set {
                this.translated_IncludeNonAllocSchedOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IncludeNegBackOrderQty {
            get {
                return this.includeNegBackOrderQtyField;
            }
            set {
                this.includeNegBackOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_IncludeNegBackOrderQty {
            get {
                return this.translated_IncludeNegBackOrderQtyField;
            }
            set {
                this.translated_IncludeNegBackOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShowValuesIn {
            get {
                return this.showValuesInField;
            }
            set {
                this.showValuesInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_ShowValuesIn {
            get {
                return this.translated_ShowValuesInField;
            }
            set {
                this.translated_ShowValuesInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RevisionRelease {
            get {
                return this.revisionReleaseField;
            }
            set {
                this.revisionReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_RevRel {
            get {
                return this.translated_RevRelField;
            }
            set {
                this.translated_RevRelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockCodeFilterType {
            get {
                return this.stockCodeFilterTypeField;
            }
            set {
                this.stockCodeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_StockCodeFilterType {
            get {
                return this.translated_StockCodeFilterTypeField;
            }
            set {
                this.translated_StockCodeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StockCodeFilterValue {
            get {
                return this.stockCodeFilterValueField;
            }
            set {
                this.stockCodeFilterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarehouseFilterType {
            get {
                return this.warehouseFilterTypeField;
            }
            set {
                this.warehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_WarehouseFilterType {
            get {
                return this.translated_WarehouseFilterTypeField;
            }
            set {
                this.translated_WarehouseFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarehouseFilterValue {
            get {
                return this.warehouseFilterValueField;
            }
            set {
                this.warehouseFilterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_DateSelection {
            get {
                return this.translated_DateSelectionField;
            }
            set {
                this.translated_DateSelectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_DateRange {
            get {
                return this.translated_DateRangeField;
            }
            set {
                this.translated_DateRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductClassFilterType {
            get {
                return this.productClassFilterTypeField;
            }
            set {
                this.productClassFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_ProductClassFilterType {
            get {
                return this.translated_ProductClassFilterTypeField;
            }
            set {
                this.translated_ProductClassFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductClassFilterValue {
            get {
                return this.productClassFilterValueField;
            }
            set {
                this.productClassFilterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BranchFilterType {
            get {
                return this.branchFilterTypeField;
            }
            set {
                this.branchFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_BranchFilterType {
            get {
                return this.translated_BranchFilterTypeField;
            }
            set {
                this.translated_BranchFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BranchFilterValue {
            get {
                return this.branchFilterValueField;
            }
            set {
                this.branchFilterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderTypeFilterType {
            get {
                return this.orderTypeFilterTypeField;
            }
            set {
                this.orderTypeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_OrderTypeFilterType {
            get {
                return this.translated_OrderTypeFilterTypeField;
            }
            set {
                this.translated_OrderTypeFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderTypeFilterValue {
            get {
                return this.orderTypeFilterValueField;
            }
            set {
                this.orderTypeFilterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyFilterType {
            get {
                return this.currencyFilterTypeField;
            }
            set {
                this.currencyFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Translated_CurrencyFilterType {
            get {
                return this.translated_CurrencyFilterTypeField;
            }
            set {
                this.translated_CurrencyFilterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyFilterValue {
            get {
                return this.currencyFilterValueField;
            }
            set {
                this.currencyFilterValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SOBacklogByStockCodeQuerySystemInformation {
        
        private string cssStyleField;
        
        private string languageField;
        
        private string decFormatField;
        
        private string dateFormatField;
        
        private string roleField;
        
        private string versionField;
        
        private string companyIdField;
        
        private string companyNameField;
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string operatorGroupField;
        
        private string operatorEmailAddressField;
        
        private string operatorLocationField;
        
        private string reportDateField;
        
        private string useSeparatorOnReportsField;
        
        private string separatorToUseField;
        
        private double noOfDigitsField;
        
        private bool noOfDigitsFieldSpecified;
        
        private string decCharToUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CssStyle {
            get {
                return this.cssStyleField;
            }
            set {
                this.cssStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DecFormat {
            get {
                return this.decFormatField;
            }
            set {
                this.decFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateFormat {
            get {
                return this.dateFormatField;
            }
            set {
                this.dateFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorGroup {
            get {
                return this.operatorGroupField;
            }
            set {
                this.operatorGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorEmailAddress {
            get {
                return this.operatorEmailAddressField;
            }
            set {
                this.operatorEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorLocation {
            get {
                return this.operatorLocationField;
            }
            set {
                this.operatorLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UseSeparatorOnReports {
            get {
                return this.useSeparatorOnReportsField;
            }
            set {
                this.useSeparatorOnReportsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeparatorToUse {
            get {
                return this.separatorToUseField;
            }
            set {
                this.separatorToUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NoOfDigits {
            get {
                return this.noOfDigitsField;
            }
            set {
                this.noOfDigitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfDigitsSpecified {
            get {
                return this.noOfDigitsFieldSpecified;
            }
            set {
                this.noOfDigitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DecCharToUse {
            get {
                return this.decCharToUseField;
            }
            set {
                this.decCharToUseField = value;
            }
        }
    }
}
