//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SYSPRO.NET.BusinessObjects.PORTMEDOC {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PostRequisitionIssue {
        
        private PostRequisitionIssueItem itemField;
        
        /// <remarks/>
        public PostRequisitionIssueItem Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostRequisitionIssueItem {
        
        private object userField;
        
        private object userPasswordField;
        
        private object eSignatureField;
        
        private object journalField;
        
        private object requisitionField;
        
        private object requisitionLineField;
        
        private object storesWarehouseField;
        
        private object binLocationField;
        
        private object lotField;
        
        private PostRequisitionIssueItemSerials serialsField;
        
        private object issueDirectToJobField;
        
        private object allocationLineNumberField;
        
        private PostRequisitionIssueItemHierarchy hierarchyField;
        
        private object referenceField;
        
        private object notationField;
        
        private object ledgerCodeField;
        
        private object passwordForLedgerCodeField;
        
        /// <remarks/>
        public object User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public object UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public object eSignature {
            get {
                return this.eSignatureField;
            }
            set {
                this.eSignatureField = value;
            }
        }
        
        /// <remarks/>
        public object Journal {
            get {
                return this.journalField;
            }
            set {
                this.journalField = value;
            }
        }
        
        /// <remarks/>
        public object Requisition {
            get {
                return this.requisitionField;
            }
            set {
                this.requisitionField = value;
            }
        }
        
        /// <remarks/>
        public object RequisitionLine {
            get {
                return this.requisitionLineField;
            }
            set {
                this.requisitionLineField = value;
            }
        }
        
        /// <remarks/>
        public object StoresWarehouse {
            get {
                return this.storesWarehouseField;
            }
            set {
                this.storesWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public object BinLocation {
            get {
                return this.binLocationField;
            }
            set {
                this.binLocationField = value;
            }
        }
        
        /// <remarks/>
        public object Lot {
            get {
                return this.lotField;
            }
            set {
                this.lotField = value;
            }
        }
        
        /// <remarks/>
        public PostRequisitionIssueItemSerials Serials {
            get {
                return this.serialsField;
            }
            set {
                this.serialsField = value;
            }
        }
        
        /// <remarks/>
        public object IssueDirectToJob {
            get {
                return this.issueDirectToJobField;
            }
            set {
                this.issueDirectToJobField = value;
            }
        }
        
        /// <remarks/>
        public object AllocationLineNumber {
            get {
                return this.allocationLineNumberField;
            }
            set {
                this.allocationLineNumberField = value;
            }
        }
        
        /// <remarks/>
        public PostRequisitionIssueItemHierarchy Hierarchy {
            get {
                return this.hierarchyField;
            }
            set {
                this.hierarchyField = value;
            }
        }
        
        /// <remarks/>
        public object Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public object Notation {
            get {
                return this.notationField;
            }
            set {
                this.notationField = value;
            }
        }
        
        /// <remarks/>
        public object LedgerCode {
            get {
                return this.ledgerCodeField;
            }
            set {
                this.ledgerCodeField = value;
            }
        }
        
        /// <remarks/>
        public object PasswordForLedgerCode {
            get {
                return this.passwordForLedgerCodeField;
            }
            set {
                this.passwordForLedgerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostRequisitionIssueItemSerials {
        
        private object serialNumberField;
        
        private object serialQuantityField;
        
        private object serialUnitsField;
        
        private object serialPiecesField;
        
        /// <remarks/>
        public object SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public object SerialQuantity {
            get {
                return this.serialQuantityField;
            }
            set {
                this.serialQuantityField = value;
            }
        }
        
        /// <remarks/>
        public object SerialUnits {
            get {
                return this.serialUnitsField;
            }
            set {
                this.serialUnitsField = value;
            }
        }
        
        /// <remarks/>
        public object SerialPieces {
            get {
                return this.serialPiecesField;
            }
            set {
                this.serialPiecesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostRequisitionIssueItemHierarchy {
        
        private object headField;
        
        private object section1Field;
        
        private object section2Field;
        
        private object section3Field;
        
        private object section4Field;
        
        /// <remarks/>
        public object Head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        public object Section1 {
            get {
                return this.section1Field;
            }
            set {
                this.section1Field = value;
            }
        }
        
        /// <remarks/>
        public object Section2 {
            get {
                return this.section2Field;
            }
            set {
                this.section2Field = value;
            }
        }
        
        /// <remarks/>
        public object Section3 {
            get {
                return this.section3Field;
            }
            set {
                this.section3Field = value;
            }
        }
        
        /// <remarks/>
        public object Section4 {
            get {
                return this.section4Field;
            }
            set {
                this.section4Field = value;
            }
        }
    }
}
