//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SYSPRO.NET.BusinessObjects.TPMTM4DOC {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PostPromotionCode {
        
        private PostPromotionCodeItem itemField;
        
        /// <remarks/>
        public PostPromotionCodeItem Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItem {
        
        private PostPromotionCodeItemActionType actionTypeField;
        
        private string promotionCodeField;
        
        private string descriptionField;
        
        private PostPromotionCodeItemGlobal globalField;
        
        private PostPromotionCodeItemTiered tieredField;
        
        private PostPromotionCodeItemPromotionType promotionTypeField;
        
        private string promotionSequenceField;
        
        private PostPromotionCodeItemPromotionSequenceGroup promotionSequenceGroupField;
        
        private PostPromotionCodeItemDateType dateTypeField;
        
        private string startDateField;
        
        private string expiryDateField;
        
        private PostPromotionCodeItemSelectionMethod selectionMethodField;
        
        private PostPromotionCodeItemStockSelection stockSelectionField;
        
        private PostPromotionCodeItemCustomerSelection customerSelectionField;
        
        private PostPromotionCodeItemPromotionBasis promotionBasisField;
        
        private PostPromotionCodeItemOffInvoice offInvoiceField;
        
        private PostPromotionCodeItemAccrual accrualField;
        
        private PostPromotionCodeItemFreeGoods freeGoodsField;
        
        private PostPromotionCodeItemTieredLinesItem tieredLinesItemField;
        
        private PostPromotionCodeItemLimits limitsField;
        
        private PostPromotionCodeItemAssociatedStock associatedStockField;
        
        private string eSignatureField;
        
        public PostPromotionCodeItem() {
            this.actionTypeField = PostPromotionCodeItemActionType.A;
            this.globalField = PostPromotionCodeItemGlobal.N;
            this.tieredField = PostPromotionCodeItemTiered.N;
            this.promotionTypeField = PostPromotionCodeItemPromotionType.O;
            this.dateTypeField = PostPromotionCodeItemDateType.R;
            this.selectionMethodField = PostPromotionCodeItemSelectionMethod.C;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemActionType ActionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PromotionCode {
            get {
                return this.promotionCodeField;
            }
            set {
                this.promotionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemGlobal Global {
            get {
                return this.globalField;
            }
            set {
                this.globalField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemTiered Tiered {
            get {
                return this.tieredField;
            }
            set {
                this.tieredField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionType PromotionType {
            get {
                return this.promotionTypeField;
            }
            set {
                this.promotionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PromotionSequence {
            get {
                return this.promotionSequenceField;
            }
            set {
                this.promotionSequenceField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionSequenceGroup PromotionSequenceGroup {
            get {
                return this.promotionSequenceGroupField;
            }
            set {
                this.promotionSequenceGroupField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemDateType DateType {
            get {
                return this.dateTypeField;
            }
            set {
                this.dateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemSelectionMethod SelectionMethod {
            get {
                return this.selectionMethodField;
            }
            set {
                this.selectionMethodField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemStockSelection StockSelection {
            get {
                return this.stockSelectionField;
            }
            set {
                this.stockSelectionField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemCustomerSelection CustomerSelection {
            get {
                return this.customerSelectionField;
            }
            set {
                this.customerSelectionField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionBasis PromotionBasis {
            get {
                return this.promotionBasisField;
            }
            set {
                this.promotionBasisField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemOffInvoice OffInvoice {
            get {
                return this.offInvoiceField;
            }
            set {
                this.offInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemAccrual Accrual {
            get {
                return this.accrualField;
            }
            set {
                this.accrualField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemFreeGoods FreeGoods {
            get {
                return this.freeGoodsField;
            }
            set {
                this.freeGoodsField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemTieredLinesItem TieredLinesItem {
            get {
                return this.tieredLinesItemField;
            }
            set {
                this.tieredLinesItemField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemLimits Limits {
            get {
                return this.limitsField;
            }
            set {
                this.limitsField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemAssociatedStock AssociatedStock {
            get {
                return this.associatedStockField;
            }
            set {
                this.associatedStockField = value;
            }
        }
        
        /// <remarks/>
        public string eSignature {
            get {
                return this.eSignatureField;
            }
            set {
                this.eSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemActionType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemGlobal {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemTiered {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemPromotionSequenceGroup {
        
        private PostPromotionCodeItemPromotionSequenceGroupMemberOfGroup memberOfGroupField;
        
        private PostPromotionCodeItemPromotionSequenceGroupGroupMax groupMaxField;
        
        public PostPromotionCodeItemPromotionSequenceGroup() {
            this.memberOfGroupField = PostPromotionCodeItemPromotionSequenceGroupMemberOfGroup.N;
            this.groupMaxField = PostPromotionCodeItemPromotionSequenceGroupGroupMax.Item0;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionSequenceGroupMemberOfGroup MemberOfGroup {
            get {
                return this.memberOfGroupField;
            }
            set {
                this.memberOfGroupField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionSequenceGroupGroupMax GroupMax {
            get {
                return this.groupMaxField;
            }
            set {
                this.groupMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionSequenceGroupMemberOfGroup {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionSequenceGroupGroupMax {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemDateType {
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemSelectionMethod {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemStockSelection {
        
        private PostPromotionCodeItemStockSelectionStockCategory stockCategoryField;
        
        private string stockCatCodeField;
        
        private string[] stockCatListItemField;
        
        private PostPromotionCodeItemStockSelectionStockCategoryType stockCategoryTypeField;
        
        private PostPromotionCodeItemStockSelectionSecStockCategory secStockCategoryField;
        
        private bool secStockCategoryFieldSpecified;
        
        private string secStockCatCodeField;
        
        private string[] secStockCatListItemField;
        
        public PostPromotionCodeItemStockSelection() {
            this.stockCategoryField = PostPromotionCodeItemStockSelectionStockCategory.Item0;
            this.stockCategoryTypeField = PostPromotionCodeItemStockSelectionStockCategoryType.Item;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemStockSelectionStockCategory StockCategory {
            get {
                return this.stockCategoryField;
            }
            set {
                this.stockCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string StockCatCode {
            get {
                return this.stockCatCodeField;
            }
            set {
                this.stockCatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StockCatListCode", IsNullable=false)]
        public string[] StockCatListItem {
            get {
                return this.stockCatListItemField;
            }
            set {
                this.stockCatListItemField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(PostPromotionCodeItemStockSelectionStockCategoryType.Item)]
        public PostPromotionCodeItemStockSelectionStockCategoryType StockCategoryType {
            get {
                return this.stockCategoryTypeField;
            }
            set {
                this.stockCategoryTypeField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemStockSelectionSecStockCategory SecStockCategory {
            get {
                return this.secStockCategoryField;
            }
            set {
                this.secStockCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecStockCategorySpecified {
            get {
                return this.secStockCategoryFieldSpecified;
            }
            set {
                this.secStockCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SecStockCatCode {
            get {
                return this.secStockCatCodeField;
            }
            set {
                this.secStockCatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SecStockCatListCode", IsNullable=false)]
        public string[] SecStockCatListItem {
            get {
                return this.secStockCatListItemField;
            }
            set {
                this.secStockCatListItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemStockSelectionStockCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemStockSelectionStockCategoryType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" ")]
        Item,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        E,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemStockSelectionSecStockCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemCustomerSelection {
        
        private string currencyField;
        
        private PostPromotionCodeItemCustomerSelectionCustomerCategory customerCategoryField;
        
        private string custCatCodeField;
        
        private string[] customerCatListItemField;
        
        private PostPromotionCodeItemCustomerSelectionCustomerCategoryType customerCategoryTypeField;
        
        private PostPromotionCodeItemCustomerSelectionSecCustomerCategory secCustomerCategoryField;
        
        private bool secCustomerCategoryFieldSpecified;
        
        private string secCustCatCodeField;
        
        private string[] secCustomerCatListItemField;
        
        private PostPromotionCodeItemCustomerSelectionApplySub applySubField;
        
        public PostPromotionCodeItemCustomerSelection() {
            this.customerCategoryField = PostPromotionCodeItemCustomerSelectionCustomerCategory.Item1;
            this.customerCategoryTypeField = PostPromotionCodeItemCustomerSelectionCustomerCategoryType.Item;
            this.applySubField = PostPromotionCodeItemCustomerSelectionApplySub.N;
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemCustomerSelectionCustomerCategory CustomerCategory {
            get {
                return this.customerCategoryField;
            }
            set {
                this.customerCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string CustCatCode {
            get {
                return this.custCatCodeField;
            }
            set {
                this.custCatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomerCatListCode", IsNullable=false)]
        public string[] CustomerCatListItem {
            get {
                return this.customerCatListItemField;
            }
            set {
                this.customerCatListItemField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemCustomerSelectionCustomerCategoryType CustomerCategoryType {
            get {
                return this.customerCategoryTypeField;
            }
            set {
                this.customerCategoryTypeField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemCustomerSelectionSecCustomerCategory SecCustomerCategory {
            get {
                return this.secCustomerCategoryField;
            }
            set {
                this.secCustomerCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecCustomerCategorySpecified {
            get {
                return this.secCustomerCategoryFieldSpecified;
            }
            set {
                this.secCustomerCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SecCustCatCode {
            get {
                return this.secCustCatCodeField;
            }
            set {
                this.secCustCatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SecCustomerCatListCode", IsNullable=false)]
        public string[] SecCustomerCatListItem {
            get {
                return this.secCustomerCatListItemField;
            }
            set {
                this.secCustomerCatListItemField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemCustomerSelectionApplySub ApplySub {
            get {
                return this.applySubField;
            }
            set {
                this.applySubField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemCustomerSelectionCustomerCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemCustomerSelectionCustomerCategoryType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" ")]
        Item,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        E,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemCustomerSelectionSecCustomerCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemCustomerSelectionApplySub {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemPromotionBasis {
        
        private PostPromotionCodeItemPromotionBasisCalculationType calculationTypeField;
        
        private string promotionValueField;
        
        private PostPromotionCodeItemPromotionBasisValueType valueTypeField;
        
        private PostPromotionCodeItemPromotionBasisThresholdType thresholdTypeField;
        
        private string thresholdField;
        
        public PostPromotionCodeItemPromotionBasis() {
            this.calculationTypeField = PostPromotionCodeItemPromotionBasisCalculationType.P;
            this.valueTypeField = PostPromotionCodeItemPromotionBasisValueType.G;
            this.thresholdTypeField = PostPromotionCodeItemPromotionBasisThresholdType.Q;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionBasisCalculationType CalculationType {
            get {
                return this.calculationTypeField;
            }
            set {
                this.calculationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PromotionValue {
            get {
                return this.promotionValueField;
            }
            set {
                this.promotionValueField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionBasisValueType ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemPromotionBasisThresholdType ThresholdType {
            get {
                return this.thresholdTypeField;
            }
            set {
                this.thresholdTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionBasisCalculationType {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionBasisValueType {
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        W,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemPromotionBasisThresholdType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        V,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemOffInvoice {
        
        private PostPromotionCodeItemOffInvoiceOffInvoiceType offInvoiceTypeField;
        
        private string productClassField;
        
        private string priceCodeField;
        
        public PostPromotionCodeItemOffInvoice() {
            this.offInvoiceTypeField = PostPromotionCodeItemOffInvoiceOffInvoiceType.L;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemOffInvoiceOffInvoiceType OffInvoiceType {
            get {
                return this.offInvoiceTypeField;
            }
            set {
                this.offInvoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductClass {
            get {
                return this.productClassField;
            }
            set {
                this.productClassField = value;
            }
        }
        
        /// <remarks/>
        public string PriceCode {
            get {
                return this.priceCodeField;
            }
            set {
                this.priceCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemOffInvoiceOffInvoiceType {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemAccrual {
        
        private string accrualTypeField;
        
        private string accrualLdgField;
        
        private string expenseLdgField;
        
        private string deductionCodeField;
        
        private string taxableField;
        
        private string taxCodeField;
        
        private string gSTableField;
        
        private string gSTCodeField;
        
        private PostPromotionCodeItemAccrualUpdateTaxChanges updateTaxChangesField;
        
        public PostPromotionCodeItemAccrual() {
            this.taxableField = "N";
            this.gSTableField = "N";
            this.updateTaxChangesField = PostPromotionCodeItemAccrualUpdateTaxChanges.N;
        }
        
        /// <remarks/>
        public string AccrualType {
            get {
                return this.accrualTypeField;
            }
            set {
                this.accrualTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccrualLdg {
            get {
                return this.accrualLdgField;
            }
            set {
                this.accrualLdgField = value;
            }
        }
        
        /// <remarks/>
        public string ExpenseLdg {
            get {
                return this.expenseLdgField;
            }
            set {
                this.expenseLdgField = value;
            }
        }
        
        /// <remarks/>
        public string DeductionCode {
            get {
                return this.deductionCodeField;
            }
            set {
                this.deductionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Taxable {
            get {
                return this.taxableField;
            }
            set {
                this.taxableField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GSTable {
            get {
                return this.gSTableField;
            }
            set {
                this.gSTableField = value;
            }
        }
        
        /// <remarks/>
        public string GSTCode {
            get {
                return this.gSTCodeField;
            }
            set {
                this.gSTCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(PostPromotionCodeItemAccrualUpdateTaxChanges.N)]
        public PostPromotionCodeItemAccrualUpdateTaxChanges UpdateTaxChanges {
            get {
                return this.updateTaxChangesField;
            }
            set {
                this.updateTaxChangesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemAccrualUpdateTaxChanges {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemFreeGoods {
        
        private string freeGoodTypeField;
        
        private string stockCodeField;
        
        private string[] freeGoodStockListItemField;
        
        private PostPromotionCodeItemFreeGoodsMethodToApply methodToApplyField;
        
        private string invoicePriceField;
        
        private string customerPriceField;
        
        private string freeGoodsPriceCodeField;
        
        private string freeGoodsProductClassField;
        
        private PostPromotionCodeItemFreeGoodsInMultipleOf inMultipleOfField;
        
        private PostPromotionCodeItemFreeGoodsRounding roundingField;
        
        private string freeGoodsThresholdField;
        
        private string qtyToShipField;
        
        public PostPromotionCodeItemFreeGoods() {
            this.methodToApplyField = PostPromotionCodeItemFreeGoodsMethodToApply.P;
            this.inMultipleOfField = PostPromotionCodeItemFreeGoodsInMultipleOf.N;
            this.roundingField = PostPromotionCodeItemFreeGoodsRounding.D;
        }
        
        /// <remarks/>
        public string FreeGoodType {
            get {
                return this.freeGoodTypeField;
            }
            set {
                this.freeGoodTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FreeGoodStockListCode", IsNullable=false)]
        public string[] FreeGoodStockListItem {
            get {
                return this.freeGoodStockListItemField;
            }
            set {
                this.freeGoodStockListItemField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemFreeGoodsMethodToApply MethodToApply {
            get {
                return this.methodToApplyField;
            }
            set {
                this.methodToApplyField = value;
            }
        }
        
        /// <remarks/>
        public string InvoicePrice {
            get {
                return this.invoicePriceField;
            }
            set {
                this.invoicePriceField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerPrice {
            get {
                return this.customerPriceField;
            }
            set {
                this.customerPriceField = value;
            }
        }
        
        /// <remarks/>
        public string FreeGoodsPriceCode {
            get {
                return this.freeGoodsPriceCodeField;
            }
            set {
                this.freeGoodsPriceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FreeGoodsProductClass {
            get {
                return this.freeGoodsProductClassField;
            }
            set {
                this.freeGoodsProductClassField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemFreeGoodsInMultipleOf InMultipleOf {
            get {
                return this.inMultipleOfField;
            }
            set {
                this.inMultipleOfField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(PostPromotionCodeItemFreeGoodsRounding.D)]
        public PostPromotionCodeItemFreeGoodsRounding Rounding {
            get {
                return this.roundingField;
            }
            set {
                this.roundingField = value;
            }
        }
        
        /// <remarks/>
        public string FreeGoodsThreshold {
            get {
                return this.freeGoodsThresholdField;
            }
            set {
                this.freeGoodsThresholdField = value;
            }
        }
        
        /// <remarks/>
        public string QtyToShip {
            get {
                return this.qtyToShipField;
            }
            set {
                this.qtyToShipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemFreeGoodsMethodToApply {
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemFreeGoodsInMultipleOf {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemFreeGoodsRounding {
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemTieredLinesItem {
        
        private string thresholdLevelField;
        
        private string thresholdToApplyField;
        
        public PostPromotionCodeItemTieredLinesItem() {
            this.thresholdLevelField = "Q";
        }
        
        /// <remarks/>
        public string ThresholdLevel {
            get {
                return this.thresholdLevelField;
            }
            set {
                this.thresholdLevelField = value;
            }
        }
        
        /// <remarks/>
        public string ThresholdToApply {
            get {
                return this.thresholdToApplyField;
            }
            set {
                this.thresholdToApplyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemLimits {
        
        private PostPromotionCodeItemLimitsBudgetLimits budgetLimitsField;
        
        private PostPromotionCodeItemLimitsStatus statusField;
        
        private PostPromotionCodeItemLimitsBudgetType budgetTypeField;
        
        private string limitField;
        
        public PostPromotionCodeItemLimits() {
            this.budgetLimitsField = PostPromotionCodeItemLimitsBudgetLimits.N;
            this.statusField = PostPromotionCodeItemLimitsStatus.A;
            this.budgetTypeField = PostPromotionCodeItemLimitsBudgetType.P;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemLimitsBudgetLimits BudgetLimits {
            get {
                return this.budgetLimitsField;
            }
            set {
                this.budgetLimitsField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemLimitsStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public PostPromotionCodeItemLimitsBudgetType BudgetType {
            get {
                return this.budgetTypeField;
            }
            set {
                this.budgetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemLimitsBudgetLimits {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemLimitsStatus {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemLimitsBudgetType {
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        V,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PostPromotionCodeItemAssociatedStock {
        
        private PostPromotionCodeItemAssociatedStockAssocStockCategory assocStockCategoryField;
        
        private string assocStockCatCodeField;
        
        private string[] assocStockCatListItemField;
        
        public PostPromotionCodeItemAssociatedStock() {
            this.assocStockCategoryField = PostPromotionCodeItemAssociatedStockAssocStockCategory.Item0;
        }
        
        /// <remarks/>
        public PostPromotionCodeItemAssociatedStockAssocStockCategory AssocStockCategory {
            get {
                return this.assocStockCategoryField;
            }
            set {
                this.assocStockCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string AssocStockCatCode {
            get {
                return this.assocStockCatCodeField;
            }
            set {
                this.assocStockCatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AssocStockCatListCode", IsNullable=false)]
        public string[] AssocStockCatListItem {
            get {
                return this.assocStockCatListItemField;
            }
            set {
                this.assocStockCatListItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PostPromotionCodeItemAssociatedStockAssocStockCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
}
